<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class AuctionSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('auctions')->insert([
            [
                'user_id'     => 3,
                'title'       => 'Laptop MacBook Air M1',
                'description' => 'MacBook Air M1 13‑inch warna Space Gray, RAM 8 GB, SSD 256 GB. Kondisi fisik 99 % mulus, baterai cycle count < 90, tidak pernah servis berat. Paket lengkap: dus, charger 30 W, kabel USB‑C asli, bonus sleeve Incase. Cocok untuk desain grafis ringan, coding, dan editing video 1080p.',
                'category_id' => 3,
                'starting_bid'=> 10000000,
                'current_bid' => 11500000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addDays(2),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction1_cover.jpg',
            ],
            [
                'user_id'     => 4,
                'title'       => 'Motor Sport Yamaha R15',
                'description' => 'Yamaha R15 V3 155 cc tahun 2022, kilometer 7.800 km. Selalu servis rutin di bengkel resmi, oli Motul ganti tiap 2.500 km. Knalpot standar (knalpot racing Akrapovic original bonus). Ban Battlax baru dipakai 3 bulan. Surat‑surat lengkap: STNK, BPKB, faktur. Siap pakai jauh ke luar kota.',
                'category_id' => 5,
                'starting_bid'=> 18000000,
                'current_bid' => 19500000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addDays(1),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction2_cover.jpg',
            ],
            [
                'user_id'     => 5,
                'title'       => 'Tanah Kavling di Bogor',
                'description' => 'Kavling hook 120 m² (8 m × 15 m) di perumahan Sierra Bogor, sertifikat SHM atas nama penjual. Jalan beton lebar 6 m, drainase rapih, listrik PLN sudah masuk. Dekat exit tol BORR, 10 menit ke stasiun LRT Cibinong. Cocok untuk dibangun rumah atau investasi karena harga tanah naik tiap tahun.',
                'category_id' => 11,
                'starting_bid'=> 60000000,
                'current_bid' => 65000000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addHours(36),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction3_cover.jpg',
            ],
            [
                'user_id'     => 6,
                'title'       => 'Ruko Siap Usaha di Palembang',
                'description' => 'Ruko 2,5 lantai luas bangunan 150 m² di jalan utama Jl. Kolonel H. Burlian Palembang. Parkiran 3 mobil, listrik 7.700 VA, air PDAM lancar. Posisi strategis dekat kampus Polsri dan bandara. Cocok untuk minimarket, kantor, atau cafe. Sertifikat HGB, IMB lengkap, siap balik nama.',
                'category_id' => 9,
                'starting_bid'=> 85000000,
                'current_bid' => 87000000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addHours(20),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction4_cover.jpg',
            ],
            [
                'user_id'     => 3,
                'title'       => 'Smartphone Samsung S21',
                'description' => 'Samsung Galaxy S21 5G warna Phantom Gray, RAM 8 GB / ROM 256 GB. Mulus 98 %, layar mulus tanpa baret (sejak awal pakai tempered glass Whitestone). Bonus original case Spigen Rugged Armor dan charger 25 W fast‑charging. IMEI resmi Indonesia, masih garansi SEIN sampai Desember 2025.',
                'category_id' => 3,
                'starting_bid'=> 6500000,
                'current_bid' => 7000000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addHours(48),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction5_cover.jpg',
            ],
            [
                'user_id'     => 4,
                'title'       => 'Mobil Innova 2019',
                'description' => 'Toyota Innova G AT Diesel 2019 warna Silver Metalik, odometer 52.000 km, service record Auto2000 lengkap. Interior bersih, jok masih plastikan bawaan, tidak pernah tabrakan atau banjir. Pajak hidup sampai Nov 2025. Bonus roof box Thule dan kaca film 3M Crystalline.',
                'category_id' => 6,
                'starting_bid'=> 125000000,
                'current_bid' => 135000000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addDays(2),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction6_cover.jpg',
            ],
            [
                'user_id'     => 5,
                'title'       => 'Hotel Mini di Jogja',
                'description' => 'Guesthouse 2 lantai dengan 7 kamar AC + kamar mandi dalam, okupansi rata‑rata 80 % (data OTA terlampir). Lokasi 300 m dari Malioboro, parkir 4 mobil, rooftop café view kota. Sertifikat SHM, izin usaha penginapan lengkap. Dijual berikut furnitur, linen, dan booking channel aktif.',
                'category_id' => 7,
                'starting_bid'=> 200000000,
                'current_bid' => 215000000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addDays(3),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction7_cover.jpg',
            ],
            [
                'user_id'     => 6,
                'title'       => 'Pabrik Kosmetik di Bekasi',
                'description' => 'Pabrik kosmetik lahan 2.500 m², bangunan 1.800 m², sertifikasi GMP & BPOM lengkap. Mesin filling cream, lotion, dan sabun cair kapasitas 5.000 pcs/jam, semua masih beroperasi. Termasuk laboratorium QC, gudang bahan baku ber‑AC, serta SDM terlatih. Omzet rata‑rata 900 jt / bulan.',
                'category_id' => 8,
                'starting_bid'=> 500000000,
                'current_bid' => 530000000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addDays(5),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction8_cover.jpg',
            ],
            [
                'user_id'     => 3,
                'title'       => 'Apartemen Sudirman Park',
                'description' => 'Unit 2BR Sudirman Park Tower A lantai 25 luas 52 m², view city lights. Full furnished: sofa IKEA, TV 55″, kitchen set Modena, water heater Ariston. Fasilitas: kolam renang, gym, minimarket 24 jam, 5 menit jalan kaki ke Stasiun MRT Setiabudi. Sertifikat Strata Title siap AJB.',
                'category_id' => 1,
                'starting_bid'=> 90000000,
                'current_bid' => 97000000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addHours(60),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction9_cover.jpg',
            ],
            [
                'user_id'     => 4,
                'title'       => 'Gudang Besar di Karawang',
                'description' => 'Gudang baja ringan 3.500 m² di Kawasan Industri KIIC Karawang. Tinggi plafon 12 m, lantai beton 20 cm, loading dock 4 pintu. Listrik 197 kVA, air bersih PAM, akses jalan truk trailer 40 ft. Cocok untuk pusat distribusi e‑commerce atau cold storage (izin IMDG siap).',
                'category_id' => 2,
                'starting_bid'=> 350000000,
                'current_bid' => 370000000,
                'start_time'  => Carbon::now('Asia/Jakarta'),
                'end_time'    => Carbon::now('Asia/Jakarta')->addDays(4),
                'status'      => 'ACTIVE',
                'winner_id'   => null,
                'image_path'  => 'storage/uploads/auction_picture/auction10_cover.jpg',
            ],
        ]);
    }
}
